module.exports = {
  extends: 'stylelint-config-xo-space',
  customSyntax: 'postcss-less',
  rules: {
    'string-quotes': [ 'double', { avoidEscape: false } ],
    'declaration-empty-line-before': null,
    'at-rule-empty-line-before': null,
    'selector-list-comma-newline-after': null,
    'rule-empty-line-before': null,
    'value-keyword-case': null, // [ 'lower', { ignoreProperties: [ 'font', 'font-family' ] } ],
    'declaration-block-no-duplicate-properties': [ true, { ignore: [ 'consecutive-duplicates' ] } ],
    'no-unknown-animations': null,
    'function-no-unknown': null,
    'declaration-property-value-disallowed-list': null,
    'font-weight-notation': null,
    'no-descending-specificity': null,
    'selector-max-compound-selectors': null,
    'block-no-empty': [ true, { ignore: [] } ],
  },
}
